FROM ubuntu:22.10
ENV PIP_ROOT_USER_ACTION=ignore
COPY ./mysite/requirements.txt /home
RUN apt-get -qq update && apt-get -qq install python3-pip && \
pip3 install pip --upgrade && pip install -r /home/requirements.txt && mkdir /my_project

